### ISSUE TITLE
User Calendars are getting updated with type as -1 and inner calendars with type as 0

### ISSUE THREAD

**Issue by purani** [thomasdayman/XrmToolBox_BulkUpdateWorkHours#1]
@thomasdayman Can you please address this issue. The code currently sets the type of user Calendar to -1.
//Please refer to here for Calander Types https://msdn.microsoft.com/en-us/library/dn689038.aspx
 userCalendarEntity.Attributes["type"] = new OptionSetValue(-1);

Can you please set the type for the new inner calendar before calling create.
newInnerCalendar.Attributes["type"] = new OptionSetValue(-1);

**Comment by thomasdayman** [comment]
Hi @purani, Sorry I didn't see this message sooner. Is this the change that is needed? (the 3rd line below)

```
Entity newInnerCalendar = new Entity("calendar");
newInnerCalendar.Attributes["businessunitid"] = new EntityReference("businessunit", ((EntityReference)(userCalendarEntity["businessunitid"])).Id);
newInnerCalendar.Attributes["type"] = new OptionSetValue(-1);
Guid innerCalendarId = organizationService.Create(newInnerCalendar);
```

**Comment by purani** [comment]
Hi @thomasdayman thanks for looking into this. I think these are the changes needed.
![image](https://user-images.githubusercontent.com/1597218/110512749-7e736280-812b-11eb-9817-0554a4f5cf9b.png)

**Comment by thomasdayman** [comment]
@purani From the Microsoft documentation it seems to make sense that these values you highlighted need changing.

I have tested the changes and published the updated version of the tool, the new version should hopefully be live on the XrmToolBox Library soon.

Let me know if it resolves your issue and I will close.

**Comment by purani** [comment]
@thomasdayman Thanks for validating the changes. I still don't see the updates in the master branch (https://github.com/thomasdayman/XrmToolBox_BulkUpdateWorkHours/blob/main/BulkUpdateWorkHours/MyPluginControl.cs). Can you please update here as well.
Also, I would like to verify once with the new version of the tool and then close this issue. Can you please let me know when a new version with your fix is available.

**Comment by thomasdayman** [comment]
The plugin has been updated and has been published the the XRMToolBox Library
