### ISSUE TITLE
Cannot retrieve more than 5000 records

### ISSUE THREAD

**Issue by eromerof** [thomasdayman/XrmToolBox_BulkUpdateWorkHours#2]
Hello Thomas,

I love your tool and thank you so much for your contribution. I have a problem because in my organization I have over 5000 records of bookableresource entity and there is no way to recover more. Would it be possible to add a field to be able to choose the fetch xml that we want??

Thank you so much ☺️

**Comment by thomasdayman** [comment]
Thanks eromerof,

I will take this feedback on board and will plan it for the next release. I'm not sure when that will be but I will leave this issue open and close it when it is complete.

**Comment by thomasdayman** [comment]
@eromerof I have applied an update to allow custom FetchXML. Please feel free to close this issue if this has solved the problem.

**Comment by eromerof** [comment]
Thank you so much Thomas. 

Great work, this new feature is very useful for me and for my customer ☺️
